
package Vistadecreaciondetabla;

import Vista.TextPrompt;

/**
 *
 * @author Brian
 */
public class CreacionTabla extends javax.swing.JFrame {

    /**
     * Creates new form CreacionTabla
     */
    public CreacionTabla() {
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt placeNE= new TextPrompt("Nombre del esquema",NombreEsquema);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraSuperior = new javax.swing.JPanel();
        GBDLabel = new javax.swing.JLabel();
        MinimizarButton = new javax.swing.JButton();
        Exitbutton = new javax.swing.JButton();
        ESQPanel = new javax.swing.JPanel();
        ESQLabel = new javax.swing.JLabel();
        InicioPanel = new javax.swing.JPanel();
        InicioLabel = new javax.swing.JLabel();
        CreacionESQPanel = new javax.swing.JPanel();
        CrearEsqLabel = new javax.swing.JLabel();
        BSD1Label = new javax.swing.JLabel();
        NewTable1 = new javax.swing.JLabel();
        Tabla1Label = new javax.swing.JLabel();
        NewTable2 = new javax.swing.JLabel();
        BSD2Label = new javax.swing.JLabel();
        Tabla1Label2 = new javax.swing.JLabel();
        NewTable3 = new javax.swing.JLabel();
        Tabla1Label3 = new javax.swing.JLabel();
        NewTable4 = new javax.swing.JLabel();
        BSD4Label = new javax.swing.JLabel();
        Tabla1Label4 = new javax.swing.JLabel();
        BSD3Label = new javax.swing.JLabel();
        TitutloBSD = new javax.swing.JLabel();
        CrearEsquemaField = new javax.swing.JTextField();
        NombreEsquema = new javax.swing.JTextField();
        CotejamientoBox = new javax.swing.JComboBox<>();
        CrearBoton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        EsquemaCOTField = new javax.swing.JTextField();
        BSD1Box = new javax.swing.JCheckBox();
        CotBSD1Label = new javax.swing.JLabel();
        BSD2Box = new javax.swing.JCheckBox();
        COT2BSD2 = new javax.swing.JLabel();
        BSD3Box = new javax.swing.JCheckBox();
        BSD4Box = new javax.swing.JCheckBox();
        COT3BSD3 = new javax.swing.JLabel();
        COT4BSD4 = new javax.swing.JLabel();
        SeleccionartodoBox = new javax.swing.JCheckBox();
        EliminarBoton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        BarraSuperior.setBackground(new java.awt.Color(255, 255, 255));

        GBDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GBDLabel.setText("Gestor de Base de Datos");

        MinimizarButton.setBackground(new java.awt.Color(0, 0, 0));
        MinimizarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MinimizarButton.setForeground(new java.awt.Color(255, 255, 255));
        MinimizarButton.setText("—");
        MinimizarButton.setToolTipText("");
        MinimizarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MinimizarButton.setBorderPainted(false);
        MinimizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarButtonMouseClicked(evt);
            }
        });
        MinimizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarButtonActionPerformed(evt);
            }
        });

        Exitbutton.setBackground(new java.awt.Color(255, 0, 51));
        Exitbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exitbutton.setForeground(new java.awt.Color(255, 255, 255));
        Exitbutton.setText("X");
        Exitbutton.setToolTipText("");
        Exitbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exitbutton.setBorderPainted(false);
        Exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GBDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinimizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGroup(BarraSuperiorLayout.createSequentialGroup()
                        .addComponent(GBDLabel)
                        .addContainerGap())
                    .addComponent(Exitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ESQPanel.setBackground(new java.awt.Color(102, 51, 0));

        ESQLabel.setBackground(new java.awt.Color(102, 51, 0));
        ESQLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ESQLabel.setForeground(new java.awt.Color(255, 255, 255));
        ESQLabel.setText("    Esquemas");

        javax.swing.GroupLayout ESQPanelLayout = new javax.swing.GroupLayout(ESQPanel);
        ESQPanel.setLayout(ESQPanelLayout);
        ESQPanelLayout.setHorizontalGroup(
            ESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ESQPanelLayout.createSequentialGroup()
                .addComponent(ESQLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        ESQPanelLayout.setVerticalGroup(
            ESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ESQPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ESQLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InicioPanel.setBackground(new java.awt.Color(0, 0, 0));

        InicioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InicioLabel.setForeground(new java.awt.Color(255, 255, 255));
        InicioLabel.setText("Inicio");

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InicioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InicioLabel)
                .addContainerGap())
        );

        CreacionESQPanel.setBackground(new java.awt.Color(204, 204, 204));

        CrearEsqLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CrearEsqLabel.setForeground(new java.awt.Color(255, 255, 255));
        CrearEsqLabel.setText("°-Crear Esquema");

        BSD1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BSD1Label.setForeground(new java.awt.Color(255, 255, 255));
        BSD1Label.setText("*Base de datos 1");

        NewTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewTable1.setForeground(new java.awt.Color(255, 255, 255));
        NewTable1.setText("+Nueva tabla");

        Tabla1Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tabla1Label.setForeground(new java.awt.Color(255, 255, 255));
        Tabla1Label.setText("Tabla 1");

        NewTable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewTable2.setForeground(new java.awt.Color(255, 255, 255));
        NewTable2.setText("+Nueva tabla");

        BSD2Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BSD2Label.setForeground(new java.awt.Color(255, 255, 255));
        BSD2Label.setText("*Base de datos 2");

        Tabla1Label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tabla1Label2.setForeground(new java.awt.Color(255, 255, 255));
        Tabla1Label2.setText("Tabla 1");

        NewTable3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewTable3.setForeground(new java.awt.Color(255, 255, 255));
        NewTable3.setText("+Nueva tabla");

        Tabla1Label3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tabla1Label3.setForeground(new java.awt.Color(255, 255, 255));
        Tabla1Label3.setText("Tabla 1");

        NewTable4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NewTable4.setForeground(new java.awt.Color(255, 255, 255));
        NewTable4.setText("+Nueva tabla");

        BSD4Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BSD4Label.setForeground(new java.awt.Color(255, 255, 255));
        BSD4Label.setText("*Base de datos 4");

        Tabla1Label4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tabla1Label4.setForeground(new java.awt.Color(255, 255, 255));
        Tabla1Label4.setText("Tabla 1");

        BSD3Label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BSD3Label.setForeground(new java.awt.Color(255, 255, 255));
        BSD3Label.setText("*Base de datos 3");

        javax.swing.GroupLayout CreacionESQPanelLayout = new javax.swing.GroupLayout(CreacionESQPanel);
        CreacionESQPanel.setLayout(CreacionESQPanelLayout);
        CreacionESQPanelLayout.setHorizontalGroup(
            CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearEsqLabel)
                    .addComponent(BSD1Label)
                    .addComponent(BSD2Label)
                    .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NewTable1)
                            .addComponent(NewTable2)
                            .addComponent(BSD3Label)
                            .addComponent(BSD4Label)
                            .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tabla1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tabla1Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NewTable3)
                                    .addComponent(NewTable4)
                                    .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Tabla1Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Tabla1Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        CreacionESQPanelLayout.setVerticalGroup(
            CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearEsqLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSD1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewTable1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabla1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSD2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewTable2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabla1Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSD3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewTable3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabla1Label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSD4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewTable4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tabla1Label4)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        TitutloBSD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TitutloBSD.setText("Bases de datos");

        CrearEsquemaField.setEditable(false);
        CrearEsquemaField.setBackground(new java.awt.Color(204, 204, 204));
        CrearEsquemaField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearEsquemaField.setText("+Crear nuevo esquema");
        CrearEsquemaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEsquemaFieldActionPerformed(evt);
            }
        });

        CotejamientoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "utf8mb4_unicode_ci" }));
        CotejamientoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotejamientoBoxActionPerformed(evt);
            }
        });

        CrearBoton.setBackground(new java.awt.Color(0, 102, 0));
        CrearBoton.setForeground(new java.awt.Color(255, 255, 255));
        CrearBoton.setText("Crear");
        CrearBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBotonActionPerformed(evt);
            }
        });

        EsquemaCOTField.setEditable(false);
        EsquemaCOTField.setBackground(new java.awt.Color(204, 204, 204));
        EsquemaCOTField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EsquemaCOTField.setText("         Esquema                  Cotejamiento");
        EsquemaCOTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsquemaCOTFieldActionPerformed(evt);
            }
        });

        BSD1Box.setText("Base de datos 1");

        CotBSD1Label.setText("utf8mb4_unicode_ci");

        BSD2Box.setText("Base de datos 2");

        COT2BSD2.setText("utf8mb4_unicode_ci ");

        BSD3Box.setText("Base de datos 3");
        BSD3Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSD3BoxActionPerformed(evt);
            }
        });

        BSD4Box.setText("Base de datos 4");

        COT3BSD3.setText("utf8mb4_unicode_ci ");

        COT4BSD4.setText("utf8mb4_unicode_ci ");

        SeleccionartodoBox.setBackground(new java.awt.Color(204, 204, 204));
        SeleccionartodoBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SeleccionartodoBox.setForeground(new java.awt.Color(255, 255, 255));
        SeleccionartodoBox.setText("Seleccionar todo");

        EliminarBoton.setBackground(java.awt.Color.red);
        EliminarBoton.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ESQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InicioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(CreacionESQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EsquemaCOTField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SeleccionartodoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EliminarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearEsquemaField)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TitutloBSD, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(BSD4Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BSD3Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BSD2Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BSD1Box, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(46, 46, 46)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(CotBSD1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(16, 16, 16))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(COT2BSD2)
                                                            .addGap(14, 14, 14))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(COT3BSD3)
                                                            .addGap(13, 13, 13))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(COT4BSD4)
                                                    .addGap(13, 13, 13))))
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(NombreEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CotejamientoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CrearBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InicioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ESQPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreacionESQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitutloBSD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrearEsquemaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CotejamientoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrearBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EsquemaCOTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeleccionartodoBox)
                            .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BSD1Box)
                            .addComponent(CotBSD1Label))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BSD2Box)
                            .addComponent(COT2BSD2))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BSD3Box)
                            .addComponent(COT3BSD3))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BSD4Box)
                            .addComponent(COT4BSD4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarButtonMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarButtonMouseClicked

    private void MinimizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarButtonActionPerformed

    }//GEN-LAST:event_MinimizarButtonActionPerformed

    private void ExitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbuttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitbuttonActionPerformed

    private void CrearEsquemaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEsquemaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearEsquemaFieldActionPerformed

    private void CrearBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearBotonActionPerformed

    private void EsquemaCOTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsquemaCOTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EsquemaCOTFieldActionPerformed

    private void BSD3BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSD3BoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BSD3BoxActionPerformed

    private void CotejamientoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotejamientoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CotejamientoBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreacionTabla().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BSD1Box;
    private javax.swing.JLabel BSD1Label;
    private javax.swing.JCheckBox BSD2Box;
    private javax.swing.JLabel BSD2Label;
    private javax.swing.JCheckBox BSD3Box;
    private javax.swing.JLabel BSD3Label;
    private javax.swing.JCheckBox BSD4Box;
    private javax.swing.JLabel BSD4Label;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JLabel COT2BSD2;
    private javax.swing.JLabel COT3BSD3;
    private javax.swing.JLabel COT4BSD4;
    private javax.swing.JLabel CotBSD1Label;
    private javax.swing.JComboBox<String> CotejamientoBox;
    private javax.swing.JPanel CreacionESQPanel;
    private javax.swing.JButton CrearBoton;
    private javax.swing.JLabel CrearEsqLabel;
    private javax.swing.JTextField CrearEsquemaField;
    private javax.swing.JLabel ESQLabel;
    private javax.swing.JPanel ESQPanel;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JTextField EsquemaCOTField;
    private javax.swing.JButton Exitbutton;
    private javax.swing.JLabel GBDLabel;
    private javax.swing.JLabel InicioLabel;
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JButton MinimizarButton;
    private javax.swing.JLabel NewTable1;
    private javax.swing.JLabel NewTable2;
    private javax.swing.JLabel NewTable3;
    private javax.swing.JLabel NewTable4;
    private javax.swing.JTextField NombreEsquema;
    private javax.swing.JCheckBox SeleccionartodoBox;
    private javax.swing.JLabel Tabla1Label;
    private javax.swing.JLabel Tabla1Label2;
    private javax.swing.JLabel Tabla1Label3;
    private javax.swing.JLabel Tabla1Label4;
    private javax.swing.JLabel TitutloBSD;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
