
package Vistadecreaciondetabla;

import conn.Connections;
import conn.MySQLConnection;
import java.util.List;
import javax.swing.DefaultListModel;
import vistas.TextPrompt;

/**
 *
 * @author Brian
 */ 
//probando clase de creeacion de tbala
public class CreacionEsquema extends javax.swing.JFrame {
DefaultListModel hardawre = new DefaultListModel();
private CreacionTabla VistaTabla;
    private DefaultListModel<String> listaModelo;
    MySQLConnection conexiones = new MySQLConnection();
    /**
     * Creates new form CreacionTabla
     */
    public CreacionEsquema() {
        initComponents();
        hardawre=new DefaultListModel();
        ListG.setModel(hardawre);
        listaModelo = new DefaultListModel<>();
        ListG.setModel(listaModelo);
        this.setLocationRelativeTo(null);
        TextPrompt placeNE= new TextPrompt("Nombre del esquema",NombreEsquema);
        updateList();
    }
    
    public void updateList() {
        List <String> schemaNames;
        schemaNames = conexiones.getSchemasName();
        for (String schema: schemaNames) {
            this.listaModelo.addElement(schema);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraSuperior = new javax.swing.JPanel();
        GBDLabel = new javax.swing.JLabel();
        MinimizarButton = new javax.swing.JButton();
        Exitbutton = new javax.swing.JButton();
        ESQPanel = new javax.swing.JPanel();
        ESQLabel = new javax.swing.JLabel();
        InicioPanel = new javax.swing.JPanel();
        InicioLabel = new javax.swing.JLabel();
        CreacionESQPanel = new javax.swing.JPanel();
        CrearEsqLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListG = new javax.swing.JList<>();
        AbrirT = new javax.swing.JButton();
        TitutloBSD = new javax.swing.JLabel();
        CrearEsquemaField = new javax.swing.JTextField();
        NombreEsquema = new javax.swing.JTextField();
        CotejamientoBox = new javax.swing.JComboBox<>();
        CrearBoton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        BarraSuperior.setBackground(new java.awt.Color(255, 255, 255));

        GBDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GBDLabel.setText("Gestor de Base de Datos");

        MinimizarButton.setBackground(new java.awt.Color(0, 0, 0));
        MinimizarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MinimizarButton.setForeground(new java.awt.Color(255, 255, 255));
        MinimizarButton.setText("—");
        MinimizarButton.setToolTipText("");
        MinimizarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MinimizarButton.setBorderPainted(false);
        MinimizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarButtonMouseClicked(evt);
            }
        });
        MinimizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarButtonActionPerformed(evt);
            }
        });

        Exitbutton.setBackground(new java.awt.Color(255, 0, 51));
        Exitbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exitbutton.setForeground(new java.awt.Color(255, 255, 255));
        Exitbutton.setText("X");
        Exitbutton.setToolTipText("");
        Exitbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exitbutton.setBorderPainted(false);
        Exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GBDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MinimizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addGroup(BarraSuperiorLayout.createSequentialGroup()
                        .addComponent(GBDLabel)
                        .addContainerGap())
                    .addComponent(Exitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ESQPanel.setBackground(new java.awt.Color(102, 51, 0));

        ESQLabel.setBackground(new java.awt.Color(102, 51, 0));
        ESQLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ESQLabel.setForeground(new java.awt.Color(255, 255, 255));
        ESQLabel.setText("    Esquemas");

        javax.swing.GroupLayout ESQPanelLayout = new javax.swing.GroupLayout(ESQPanel);
        ESQPanel.setLayout(ESQPanelLayout);
        ESQPanelLayout.setHorizontalGroup(
            ESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ESQPanelLayout.createSequentialGroup()
                .addComponent(ESQLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        ESQPanelLayout.setVerticalGroup(
            ESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ESQPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ESQLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InicioPanel.setBackground(new java.awt.Color(0, 0, 0));

        InicioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        InicioLabel.setForeground(new java.awt.Color(255, 255, 255));
        InicioLabel.setText("Inicio");

        javax.swing.GroupLayout InicioPanelLayout = new javax.swing.GroupLayout(InicioPanel);
        InicioPanel.setLayout(InicioPanelLayout);
        InicioPanelLayout.setHorizontalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InicioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        InicioPanelLayout.setVerticalGroup(
            InicioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InicioLabel)
                .addContainerGap())
        );

        CreacionESQPanel.setBackground(new java.awt.Color(204, 204, 204));

        CrearEsqLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CrearEsqLabel.setForeground(new java.awt.Color(255, 255, 255));
        CrearEsqLabel.setText("°-Crear Esquema");
        CrearEsqLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearEsqLabelMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(ListG);

        AbrirT.setText("Usar Esequema");
        AbrirT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreacionESQPanelLayout = new javax.swing.GroupLayout(CreacionESQPanel);
        CreacionESQPanel.setLayout(CreacionESQPanelLayout);
        CreacionESQPanelLayout.setHorizontalGroup(
            CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                .addGroup(CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                        .addGroup(CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CrearEsqLabel))
                            .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(AbrirT, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CreacionESQPanelLayout.setVerticalGroup(
            CreacionESQPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreacionESQPanelLayout.createSequentialGroup()
                .addComponent(CrearEsqLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AbrirT)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        TitutloBSD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TitutloBSD.setText("Bases de datos");

        CrearEsquemaField.setEditable(false);
        CrearEsquemaField.setBackground(new java.awt.Color(204, 204, 204));
        CrearEsquemaField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearEsquemaField.setText("+Crear nuevo esquema");
        CrearEsquemaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEsquemaFieldActionPerformed(evt);
            }
        });

        NombreEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEsquemaActionPerformed(evt);
            }
        });

        CotejamientoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "utf8mb4_unicode_ci" }));
        CotejamientoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotejamientoBoxActionPerformed(evt);
            }
        });

        CrearBoton.setBackground(new java.awt.Color(0, 102, 0));
        CrearBoton.setForeground(new java.awt.Color(255, 255, 255));
        CrearBoton.setText("Crear");
        CrearBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ESQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InicioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(CreacionESQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearEsquemaField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TitutloBSD, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(NombreEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CotejamientoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CrearBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InicioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ESQPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreacionESQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitutloBSD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CrearEsquemaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreEsquema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CotejamientoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CrearBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarButtonMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarButtonMouseClicked

    private void MinimizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarButtonActionPerformed

    }//GEN-LAST:event_MinimizarButtonActionPerformed

    private void ExitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbuttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitbuttonActionPerformed

    private void CrearEsquemaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEsquemaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearEsquemaFieldActionPerformed

    private void CrearBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBotonActionPerformed
        
        updateList();
    }//GEN-LAST:event_CrearBotonActionPerformed

    private void CotejamientoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotejamientoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CotejamientoBoxActionPerformed

    private void NombreEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEsquemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEsquemaActionPerformed

    private void CrearEsqLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearEsqLabelMouseClicked
        // TODO add your handling code here:
            CreacionEsquema newframe = new CreacionEsquema();
            
            newframe.setVisible(true);
            
            this.dispose();
            
    }//GEN-LAST:event_CrearEsqLabelMouseClicked

    private void AbrirTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirTActionPerformed
        // TODO add your handling code here:
        String elementoSeleccionado = ListG.getSelectedValue();
        if (elementoSeleccionado != null) {
            VistaTabla = new CreacionTabla(elementoSeleccionado);
            VistaTabla.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_AbrirTActionPerformed

    public void crearSchema() {
        conexiones.setSchema(this.NombreEsquema.getText());
        
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionEsquema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionEsquema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionEsquema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionEsquema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CreacionEsquema().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirT;
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JComboBox<String> CotejamientoBox;
    private javax.swing.JPanel CreacionESQPanel;
    private javax.swing.JButton CrearBoton;
    private javax.swing.JLabel CrearEsqLabel;
    private javax.swing.JTextField CrearEsquemaField;
    private javax.swing.JLabel ESQLabel;
    private javax.swing.JPanel ESQPanel;
    private javax.swing.JButton Exitbutton;
    private javax.swing.JLabel GBDLabel;
    private javax.swing.JLabel InicioLabel;
    private javax.swing.JPanel InicioPanel;
    private javax.swing.JList<String> ListG;
    private javax.swing.JButton MinimizarButton;
    private javax.swing.JTextField NombreEsquema;
    private javax.swing.JLabel TitutloBSD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
