package vistas;

import conn.*;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Brian
 */
public class VistaSeleccion extends javax.swing.JFrame {
    private Connections conexiones = new Connections();
    Conexion selectedConexion;
    /**
     * Creates new form VistaSeleccion
     */
    public VistaSeleccion() {
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        TextPrompt placeserv = new TextPrompt("Mysql@127.0.0.1:3306", ServicioTextField);
        TextPrompt placeusr = new TextPrompt("Dueño de la conexión", UsuarioTextField);
        
        actualizarSelector();
    }
    
    public void actualizarSelector() {
        ArrayList<String> nombresCon;
        nombresCon = conexiones.getNombresConexiones();
        
        for(String nombre: nombresCon) {
            this.DNSBox.addItem(nombre);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraSuperior = new javax.swing.JPanel();
        TextoConexion = new javax.swing.JLabel();
        Exitbutton = new javax.swing.JButton();
        MinimizarButton = new javax.swing.JButton();
        DNSLabel = new javax.swing.JLabel();
        DNSBox = new javax.swing.JComboBox<>();
        ServicioLabel = new javax.swing.JLabel();
        ServicioTextField = new javax.swing.JTextField();
        UsuarioLabel = new javax.swing.JLabel();
        UsuarioTextField = new javax.swing.JTextField();
        ContraselaLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ConectarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();
        EliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        BarraSuperior.setBackground(new java.awt.Color(255, 255, 255));

        TextoConexion.setText("Selecionar Conexión");

        Exitbutton.setBackground(new java.awt.Color(255, 0, 51));
        Exitbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exitbutton.setForeground(new java.awt.Color(255, 255, 255));
        Exitbutton.setText("X");
        Exitbutton.setToolTipText("");
        Exitbutton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exitbutton.setBorderPainted(false);
        Exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbuttonActionPerformed(evt);
            }
        });

        MinimizarButton.setBackground(new java.awt.Color(0, 0, 0));
        MinimizarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MinimizarButton.setForeground(new java.awt.Color(255, 255, 255));
        MinimizarButton.setText("—");
        MinimizarButton.setToolTipText("");
        MinimizarButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MinimizarButton.setBorderPainted(false);
        MinimizarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarButtonMouseClicked(evt);
            }
        });
        MinimizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BarraSuperiorLayout = new javax.swing.GroupLayout(BarraSuperior);
        BarraSuperior.setLayout(BarraSuperiorLayout);
        BarraSuperiorLayout.setHorizontalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraSuperiorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(TextoConexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MinimizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        BarraSuperiorLayout.setVerticalGroup(
            BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BarraSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BarraSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exitbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MinimizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextoConexion))
                .addContainerGap())
        );

        DNSLabel.setText("DNS:");

        DNSBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una conexión" }));
        DNSBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNSBoxActionPerformed(evt);
            }
        });

        ServicioLabel.setText("Servicio:");

        ServicioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicioTextFieldActionPerformed(evt);
            }
        });

        UsuarioLabel.setText("Usuario:");

        UsuarioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioTextFieldActionPerformed(evt);
            }
        });

        ContraselaLabel.setText("Contraseña:");

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        ConectarButton.setBackground(new java.awt.Color(0, 204, 0));
        ConectarButton.setForeground(new java.awt.Color(255, 255, 255));
        ConectarButton.setText("Conectar");
        ConectarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarButtonActionPerformed(evt);
            }
        });

        CancelarButton.setBackground(new java.awt.Color(255, 0, 51));
        CancelarButton.setForeground(new java.awt.Color(255, 255, 255));
        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        EliminarButton.setBackground(new java.awt.Color(153, 0, 51));
        EliminarButton.setForeground(new java.awt.Color(255, 255, 255));
        EliminarButton.setText("Eliminar");
        EliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(UsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ServicioLabel)
                        .addComponent(DNSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ContraselaLabel)
                    .addComponent(ConectarButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DNSBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ServicioTextField)
                            .addComponent(UsuarioTextField)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(EliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelarButton)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNSLabel)
                    .addComponent(DNSBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServicioLabel)
                    .addComponent(ServicioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraselaLabel)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConectarButton)
                    .addComponent(CancelarButton)
                    .addComponent(EliminarButton))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbuttonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitbuttonActionPerformed

    private void MinimizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizarButtonActionPerformed

    }//GEN-LAST:event_MinimizarButtonActionPerformed

    private void ServicioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicioTextFieldActionPerformed

    }//GEN-LAST:event_ServicioTextFieldActionPerformed

    private void DNSBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNSBoxActionPerformed
        // TODO add your handling code here:
        String selectedNombre = (String) this.DNSBox.getSelectedItem();
        if (selectedNombre != null) {
            selectedConexion = conexiones.buscarConexion(selectedNombre);
            if (selectedConexion != null) {
                this.ServicioTextField.setText(selectedConexion.url);
                this.UsuarioTextField.setText(selectedConexion.user);
                this.PasswordField.setText(selectedConexion.password);
            }
        }
    }//GEN-LAST:event_DNSBoxActionPerformed

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
        setVisible(false);
        Ventana_Ini frame = new Ventana_Ini();
        frame.setVisible(true);
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void ConectarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarButtonActionPerformed
        MySQLConnection conn = new MySQLConnection();
        String selectedNombre = (String) this.DNSBox.getSelectedItem();
        String nuevaURL = this.ServicioTextField.getText();
        if (selectedNombre != null && !nuevaURL.isEmpty()) {
            conexiones.editarConexion(selectedNombre, nuevaURL);
        }
        
        conn.setConnection(selectedConexion);
        
        try {
            conn.openConnection();
        } catch (SQLException ex) {
            Logger.getLogger(VistaSeleccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConectarButtonActionPerformed

    private void UsuarioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioTextFieldActionPerformed

    private void MinimizarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarButtonMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MinimizarButtonMouseClicked

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarButtonActionPerformed
        // TODO add your handling code here:
        String selectedNombre = (String) this.DNSBox.getSelectedItem();
        if (selectedNombre != null) {
            conexiones.eliminarConexion(selectedNombre);
            this.DNSBox.removeItem(selectedNombre); // Elimina el elemento del JComboBox
        }
        this.ServicioTextField.setText("");
        this.UsuarioTextField.setText("");
        this.PasswordField.setText("");
    }//GEN-LAST:event_EliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraSuperior;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JButton ConectarButton;
    private javax.swing.JLabel ContraselaLabel;
    private javax.swing.JComboBox<String> DNSBox;
    private javax.swing.JLabel DNSLabel;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JButton Exitbutton;
    private javax.swing.JButton MinimizarButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel ServicioLabel;
    private javax.swing.JTextField ServicioTextField;
    private javax.swing.JLabel TextoConexion;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JTextField UsuarioTextField;
    // End of variables declaration//GEN-END:variables
}
